version: 2.1

build-cypress-image: &build-cypress-image
  image: cypress/browsers:node14.17.0-chrome88-ff89

aliases:
  - &ignore-main-branch
    branches:
      ignore: main
  - &only-main-branch
    branches:
      only: main

commands:
  yarn-install:
    description: Install cached yarn packages
    steps:
      - restore_cache:
          keys: ['v3-{{ checksum "yarn.lock" }}']
      - run: yarn config set yarn-offline-mirror /tmp/project/.cache/yarn
      - run: yarn install --frozen-lockfile

  yarn-save-cache:
    description: Save yarn packages cache
    steps:
      - run: mkdir -p /tmp/project/.cache
      - run: chmod +rw /tmp/project/.cache
      - save_cache:
          key: v3-{{ checksum "yarn.lock" }}
          paths: ["/tmp/project/.cache"]

jobs:
  build:
    working_directory: /tmp/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run: yarn build

  unit-tests:
    working_directory: /tmp/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run: yarn test

  integration-tests:
    working_directory: /tmp/project
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run: yarn test:integration

  e2e-tests:
    working_directory: /tmp/project
    docker:
      - *build-cypress-image
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run:
          name: Running e2e tests
          command: yarn test:e2e

workflows:
  build-and-test:
    jobs:
      - build:
          filters: *ignore-main-branch
      - unit-tests:
          filters: *ignore-main-branch
      - integration-tests:
          filters: *ignore-main-branch
      - e2e-tests:
          requires:
            - build
            - integration-tests
            - e2e-tests

  main:
    jobs:
      - build:
          filters: *only-main-branch
      - unit-tests:
          filters: *only-main-branch
      - integration-tests:
          filters: *only-main-branch
      - e2e-tests:
          requires:
            - build
            - integration-tests
            - e2e-tests
