version: 2.1

aliases:
  - &working_directory
    working_directory: /home/circleci/project/
  - &ignore-main-branch
    branches:
      ignore: main
  - &only-main-branch
    branches:
      only: main

orbs:
  cypress: cypress-io/cypress@1

commands:
  yarn-install:
    description: Install cached yarn packages
    steps:
      - restore_cache:
          keys: ['v3-{{ checksum "yarn.lock" }}']
      - run: yarn config set yarn-offline-mirror ~/.cache/yarn
      - run: yarn install --frozen-lockfile

  yarn-save-cache:
    description: Save yarn packages cache
    steps:
      - save_cache:
          key: v3-{{ checksum "yarn.lock" }}
          paths: ["~/.cache"]

jobs:
  build:
    <<: *working_directory
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run: yarn build

  unit-tests:
    <<: *working_directory
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run: yarn test

  integration-tests:
    <<: *working_directory
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run: yarn test:integration

  # e2e-tests:
  #   <<: *working_directory
  #   docker:
  #     - image: cimg/node:14.15.4
  #   steps:
  #     - checkout
  #     - yarn-install
  #     - yarn-save-cache
  #     - run:
  #         name: Running E2E tests
  #         command: |
  #           yarn test:e2e

workflows:
  build-and-test:
    jobs:
      - build:
          filters: *ignore-main-branch
      - unit-tests:
          filters: *ignore-main-branch
      - integration-tests:
          filters: *ignore-main-branch
      - cypress/run:
          yarn: true
          command: npm run test:e2e
      # - cypress/install:
      #     <<: *working_directory
      #     yarn: true

      # - e2e-tests:
      #     filters: *ignore-main-branch
      # - cypress/install:
      #     yarn: true
      #     cache-key: >-
      #       'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
      #     <<: *working_directory

  main:
    jobs:
      - build:
          filters: *only-main-branch
      - unit-tests:
          filters: *only-main-branch
      - integration-tests:
          filters: *only-main-branch
      - cypress/run:
          yarn: true
          command: npm run test:e2e
          # install-command: yarn install --frozen-lockfile
          # executor: cypress/base-12
      # - e2e-tests:
      #     filters: *only-main-branch
