version: 2.1

aliases:
  - &working_directory
    working_directory: /home/circleci/project/
  - &ignore-main-branch
    branches:
      ignore: main
  - &only-main-branch
    branches:
      only: main

commands:
  yarn-install:
    description: Install cached yarn packages
    steps:
      - restore_cache:
          keys: ['v2-{{ checksum "yarn.lock" }}']
      - run: yarn config set yarn-offline-mirror ~/.cache/yarn
      - run: yarn install --frozen-lockfile

  yarn-save-cache:
    description: Save yarn packages cache
    steps:
      - save_cache:
          key: v2-{{ checksum "yarn.lock" }}
          paths: ["~/.cache"]

jobs:
  build:
    <<: *working_directory
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run: yarn build

  unit-tests:
    <<: *working_directory
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run: yarn test

  test-integration:
    <<: *working_directory
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - yarn-install
      - yarn-save-cache
      - run: yarn test:integration

workflows:
  build-and-test:
    jobs:
      - build:
          filters: *ignore-main-branch
      - unit-tests:
          filters: *ignore-main-branch
      - integration-tests:
          filters: *ignore-main-branch

  main:
    jobs:
      - build:
          filters: *only-main-branch
      - unit-tests:
          filters: *only-main-branch
      - integration-tests:
          filters: *only-main-branch
